version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "9005:3000"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "9006:9000"
    volumes:
      - ./backend:/var/www
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/db_name

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9080:3306"
