services:
  phpmyadmin:
    image: 'phpmyadmin'
    restart: always
    ports:
      - '4080:80'
    environment:
      UPLOAD_LIMIT: '500M'
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: pass
    depends_on:
      - mysql

  mysql:
    image: 'mysql'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ui_test

  frontend:
    container_name: 'frontend'
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '9005:3000'
    volumes:
      - './frontend:/app'
    environment:
      - NODE_ENV=development
    command: npm start 

  backend:
    container_name: 'backend'
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '9006:8000'
    restart: on-failure
    volumes:
      - './backend/:/var/www/symfony/'
    command: sh -c "composer install && php bin/console doctrine:schema:update --complete --force && symfony server:start --listen-ip=0.0.0.0"
    depends_on:
      mysql:
        condition: service_started

volumes:
  mysql_data: